global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: simple_server
    static_configs:
      - targets: ["webserver:8090"]
  - job_name: testingvm
    static_configs:
      - targets: ["172.18.0.1:9100"]